# Function to calculate the Total Amps used. Takes in a float list of thruster PWMs
def get_amp_total(thruster_pwms):
    amp_total = 0

    for x in range(len(thruster_pwms)):
        amp_total += 214.9513 - 0.2864872 * thruster_pwms[x] + 0.00009537964 * (thruster_pwms[x] * thruster_pwms[x])
    return amp_total


# Returns the current for a single thruster
def get_amp(thruster):
    amp = 214.9513 - 0.2864872 * thruster + 0.00009537964 * (thruster * thruster)
    return amp


# As our total limit is 100A Amps generated by each thruster cannot exceed 12.5.
# Most PWM values however don't go over this so I'm cutting off the very top and bottom end
# PWM values which will guarentee safety
def temp_safe_guard(thruster_pwms):
    for x in range(len(thruster_pwms)):
        if thruster_pwms[x] > 1800:
            thruster_pwms[x] = 1800
        elif thruster_pwms[x] < 1200:
            thruster_pwms[x] = 1200
    return thruster_pwms


pwmList = [1900.0, 1100.0, 1700.0, 1700.0, 1700.0, 1700.0, 1700.0, 1700.0]
# print(get_amp_total(pwmList));
print(temp_safe_guard(pwmList))
